### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zx121122** [mitwo-dev/platform_frameworks_native#1]
android_hardware_libhardware 这个库的4.4.2最新修改没有合入，导致编译报错。

make: **\* [out/target/product/aries/obj/SHARED_LIBRARIES/libsurfaceflinger_intermediates/Layer.o] 错误 1
make: **\* 正在等待未完成的任务....
frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp: In member function 'void android::SurfaceFlinger::doComposeSurfaces(const android::sp<const android::DisplayDevice>&, const android::Region&)':
frameworks/native/services/surfaceflinger/SurfaceFlinger.cpp:1943:26: error: 'HWC_BLIT' was not declared in this scope
make: **\* [out/target/product/aries/obj/SHARED_LIBRARIES/libsurfaceflinger_intermediates/SurfaceFlinger.o] 错误 1

**Comment by ivan19871002** [comment]
谢谢提醒，已经提交
